/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_2 (
    input [6:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  wire [16-1:0] M_shifter16_out;
  reg [7-1:0] M_shifter16_alufn;
  reg [16-1:0] M_shifter16_a;
  reg [16-1:0] M_shifter16_b;
  shifter_3 shifter16 (
    .alufn(M_shifter16_alufn),
    .a(M_shifter16_a),
    .b(M_shifter16_b),
    .out(M_shifter16_out)
  );
  
  wire [16-1:0] M_multiply16_out;
  reg [7-1:0] M_multiply16_alufn;
  reg [16-1:0] M_multiply16_a;
  reg [16-1:0] M_multiply16_b;
  multiply_4 multiply16 (
    .alufn(M_multiply16_alufn),
    .a(M_multiply16_a),
    .b(M_multiply16_b),
    .out(M_multiply16_out)
  );
  
  always @* begin
    M_shifter16_alufn = alufn;
    M_shifter16_a = a;
    M_shifter16_b = b;
    M_multiply16_alufn = alufn;
    M_multiply16_a = a;
    M_multiply16_b = b;
    out = 16'h0000;
    
    case (alufn[4+2-:3])
      3'h2: begin
        out = M_shifter16_out;
      end
      3'h4: begin
        out = M_multiply16_out;
      end
    endcase
  end
endmodule
