/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_2 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  wire [16-1:0] M_shifter16_out;
  reg [6-1:0] M_shifter16_alufn;
  reg [16-1:0] M_shifter16_a;
  reg [16-1:0] M_shifter16_b;
  shifter_3 shifter16 (
    .alufn(M_shifter16_alufn),
    .a(M_shifter16_a),
    .b(M_shifter16_b),
    .out(M_shifter16_out)
  );
  
  always @* begin
    M_shifter16_alufn = alufn;
    M_shifter16_a = a;
    M_shifter16_b = b;
    out = M_shifter16_out;
  end
endmodule
