/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_4 (
    input [6:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  wire [16-1:0] M_adder16_out;
  wire [1-1:0] M_adder16_z;
  wire [1-1:0] M_adder16_v;
  wire [1-1:0] M_adder16_n;
  reg [16-1:0] M_adder16_a;
  reg [16-1:0] M_adder16_b;
  reg [7-1:0] M_adder16_alufn;
  adder_3 adder16 (
    .a(M_adder16_a),
    .b(M_adder16_b),
    .alufn(M_adder16_alufn),
    .out(M_adder16_out),
    .z(M_adder16_z),
    .v(M_adder16_v),
    .n(M_adder16_n)
  );
  
  reg z;
  
  reg v;
  
  reg n;
  
  always @* begin
    M_adder16_alufn = 7'h01;
    M_adder16_a = a;
    M_adder16_b = b;
    z = M_adder16_z;
    v = M_adder16_v;
    n = M_adder16_n;
    out[1+14-:15] = 15'h0000;
    
    case (alufn[1+1-:2])
      2'h1: begin
        out[0+0-:1] = z;
      end
      2'h2: begin
        out[0+0-:1] = n ^ v;
      end
      2'h3: begin
        out[0+0-:1] = z | n ^ v;
      end
    endcase
  end
endmodule
