/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module divide_14 (
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    if (b == 1'h0) begin
      out = 58'h23c61b3b32571c7;
    end else begin
      out = a / b;
    end
  end
endmodule
